module.exports = {
  modulesCss: [
    'a11y',
    'effect-coverflow',
    'effect-creative',
    'effect-cube',
    'effect-fade',
    'effect-flip',
  ],
  modulesJs: [
    'keyboard',
    'mousewheel',
    'navigation',
    'pagination',
    'scrollbar',
    'lazy',
    'a11y',
    'hash-navigation',
    'autoplay',
    'effect-coverflow',
    'effect-creative',
    'effect-cube',
    'effect-fade',
    'effect-flip',
  ],
};
